## Server
server.port: ${PORT:8080}

## Spring
spring:
  profiles.active: dev

  ### Spring Data
  data:
    mongodb:
      host: localhost
      port: 27017
      database: persona
      username: root
      password: mongomongo
      authentication-database: admin

## Log
logging.level.org.hibernate:
  SQL: DEBUG
  type:
    descriptor:
      sql:
        BasicBinder: TRACE
